# isRuntimeException

Checks if a given unknown value is a `RuntimeException`.

To import and use `isRuntimeException` from the "Cause" module:

```ts
import * as Cause from "effect/Cause"
// Can be accessed like this
Cause.isRuntimeException
```

**Signature**

```ts
export declare const isRuntimeException: (u: unknown) => u is RuntimeException
```
